name: tests

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-export:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --group test .

    - name: Test with pytest
      run: |
        python -m pytest --cov=./regmmd --cov-report xml
    - name: Creating coverage folder
      run: |
        mkdir -p coverage
    - name: Coverage Badge
      run: |
        genbadge coverage -n "pytest" -i ./coverage.xml -o ./coverage/coverage_badge.svg
    - name: Export Coverage Badge 
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.TOKEN }}
        gist_id: 73b75fdbeb1fba4b08092b0af7b746f3
        file_path: ./coverage/coverage_badge.svg
        file_type: text
    
      
    
